# General Spring config
spring.application.name=cursorpagination
spring.main.banner-mode=off

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# Logging configuration with Request ID from MDC
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{requestId}] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%X{requestId}] %-5level %logger{36} - %msg%n